CREATE TABLE IF NOT EXISTS meta_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  meta_setting TEXT NOT NULL UNIQUE,
  meta_value TEXT
);

INSERT INTO meta_settings(meta_setting, meta_value)
VALUES ('demo_problem_id', NULL)
ON CONFLICT DO NOTHING;
